# Generated by Django 4.2.7 on 2023-12-16 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
