# Generated by Django 4.2.7 on 2023-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0002_alter_auction_content_alter_order_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default='Đấu giá của', max_length=255),
        ),
    ]
