# Generated by Django 4.2.7 on 2024-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
