# Generated by Django 4.2.7 on 2023-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0003_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(default='Đấu giá của ', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='Đơn hàng của ', max_length=255),
        ),
    ]
