# Generated by Django 4.2.7 on 2024-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0005_remove_order_total_money_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identityCard',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
