# Generated by Django 4.2.7 on 2024-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
