# Generated by Django 4.2.7 on 2024-02-02 17:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
