# Generated by Django 4.2.7 on 2024-02-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0010_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shipper', to=settings.AUTH_USER_MODEL),
        ),
    ]
