# Generated by Django 4.2.7 on 2024-02-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0012_alter_rating_order_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromStreet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='toStreet',
            field=models.CharField(max_length=255),
        ),
    ]
