# Generated by Django 4.2.7 on 2024-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0014_alter_order_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateField(default='2024-08-02'),
        ),
    ]
