# Generated by Django 4.2.7 on 2024-02-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0015_alter_order_deliverydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='money',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
    ]
