# Generated by Django 4.2.7 on 2024-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htproject', '0016_alter_auction_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervoucher',
            name='decreased_money',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
    ]
